### ISSUE TITLE
PushState error when attempting to scroll to Hash

### ISSUE THREAD

**Issue by Alan19** [rafgraph/react-router-hash-link#37]
When I attempt to scroll to a path with a hash fragment, I get 
`
Uncaught DOMException: Failed to execute 'pushState' on 'History': A history state object with URL 'http:/#overview' cannot be created in a document with origin 'http://localhost:3000' and URL 'http://localhost:3000/indepth/treasures'.
`.
While it does scroll to the section of the page with the text, it ends up freezing for a 1-2 seconds.

**Comment by rafrex** [comment]
This seems like something is wrong with how the code it setup. Do you have a failing example on codesandbox?

**Comment by palaniichukdmytro** [comment]
@Alan19 I suppose you have a mistake in path to

Wrong:
`/{routhe.path}/#overview `
`/{routhe.path}#overview `
