### ISSUE TITLE
On mobile apps it is not working

### ISSUE THREAD

**Issue by irfanDC** [rafgraph/react-router-hash-link#38]
All is working on the website but on the mobile navigation not working, here is the code

import React, { Component } from "react"

import { NavHashLink as NavLink } from 'react-router-hash-link';

// and the link creation script

<NavLink to={"#schedule"}</NavLink>

Note:  I am also using HashRouter as without it mobile app showing blank page.

**Comment by roeliman** [comment]
yes! got same problem here
on mobile it doesn't work at all
but perfectly work on desktop version

**Comment by rafrex** [comment]
You have to use `<BrowserRouter>`, this does not work with `<HashRouter>`.

I'm unable to reproduce an issue on mobile.. does the example site http://react-router-hash-link.rafrex.com/ work for you on mobile.. if not which device and browser? Thanks.

**Comment by alamothe** [comment]
Facing the same issue. For complex pages on iOS, it won't scroll all the way.

**Comment by rafgraph** [comment]
The demo site has the home page which links to the page with 3 sections. The scroll works fine for me, but note that when navigating to a new page it won't smooth scroll. If this is still an issue, please open a new issue and with a failing example, thanks.

**Comment by dev-cmaliwal** [comment]
I am facing the same issue, this is not working in mobile nor in responsive mode. Also, I am using `BrowseRouter`.
