### ISSUE TITLE
activeStyle does not work

### ISSUE THREAD

**Issue by mustafamamun** [rafgraph/react-router-hash-link#41]
activeStyle property for the hash routing does not work. I have reproduced it in the following url 
https://codesandbox.io/embed/w0op0r5ov7 . In code sand box it does not also scroll. I have got the scrolling working but the active link is not taking the style given.

**Comment by rafrex** [comment]
This is an issue with React Router, it seems like the fix is merged in master but not released yet.
See https://github.com/ReactTraining/react-router/issues/6877

**Comment by rafgraph** [comment]
This should be fixed in v2.2.0
