### ISSUE TITLE
Scroll to div not working for lazy loaded components

### ISSUE THREAD

**Issue by jkinney768** [rafgraph/react-router-hash-link#47]
Hello,

I'm having an issue where on page load/refresh it's not scrolling to the div with the id matching the hash. This is only when I'm lazy loading my component, otherwise it works fine. Here is a simple example that should give an outline of the problem (if a more complete/working example is needed, let me know).

```
import React, { Suspense, lazy } from 'react';
import { NavHashLink as NavLink } from 'react-router-hash-link';
import { Route } from 'react-router-dom';

const ExampleContainer = lazy(() => import('containers/ExampleContainer'));

class App extends React.Component {
    render() {
        return (
            <div>
                <div>
                    <NavLink to={'/page#somewhere'}>
                        Example Link
                    </NavLink>
                <div>
                <div>
                    <Suspense fallback={<div>Loading...</div>}>
                        <Switch>
                            <Route component={() => <ExampleContainer />}  />
                        </Switch>
                    </Suspense>
                </div>
            </div>
        );
    }
}

export default App;
```

I haven't had a ton of time to look in to the issue deeper, but since it's being lazy loaded, likely it's not able to find the ID in the DOM in time to perform the scroll.

**Comment by rafrex** [comment]
It has 10 seconds to appear in the DOM, so that's probably not it. Do you have a live failing example on codesandbox or somewhere else?

**Comment by jkinney768** [comment]
I can work on creating one. I unfortunately can not share my exact current code.
