### ISSUE TITLE
<HashLink to = {} > </HashLink> says Property 'to' doesn't exist on type 'IntrinsicAttributes'

### ISSUE THREAD

**Issue by siddhant05** [rafgraph/react-router-hash-link#48]
When I'm using <HashLink to = {}> </HashLink> ; it always throws an error that `Type '{ to: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<HashLink> & Readonly<HashLinkProps> & Readonly<{ children?: ReactNode; }>'.
  Property 'to' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<HashLink> & Readonly<HashLinkProps> & Readonly<{ children?: ReactNode; }>'.ts(2322)`

Unable to find a reason for the same. I've imported {HashLink} from 'react-router-hash-link'; Also used `lerna add --scope=common-components react-router-hash-link` to add the package. Not sure if I'm missing something here.

**Comment by rafrex** [comment]
Hi, do you have a failing example I can look at on codesandbox? Thanks.
