### ISSUE TITLE
Incompatible with `@material-ui`

### ISSUE THREAD

**Issue by vicary** [rafgraph/react-router-hash-link#61]
# Summary
Got the following error (see image below) about function component not able to contain ref, probably related to their [caveat-with-refs](https://material-ui.com/guides/composition/#caveat-with-refs).

![Screenshot 2020-02-03 at 9 01 24 PM](https://user-images.githubusercontent.com/85772/73655382-e2c22800-46c8-11ea-9054-30211b349a52.png)

Added to the problem is that there are mismatches between `@types/react-router-hash-link` where is declares itself as a class component, and the actual source code is in fact a function component, an usual fix `<Link component={React.forwardRef(HashLink)}>...</Link>` yield an eslint error (see image below).

![Screenshot 2020-02-03 at 9 09 18 PM](https://user-images.githubusercontent.com/85772/73655821-cecaf600-46c9-11ea-9a22-f1ae3c0c7e65.png)

# Workaround
A temporary workaround is to force tslint to ignore that specific line of code, but definitely suboptimal to see.

```tsx
{/*
// @ts-ignore */}
<Link component={forwardRef(HashLink)} to="/">...</Link>
```

**Comment by vicary** [comment]
Copying the author of `@types/react-router-hash-link` here, @zoompie. Issues are disabled in that fork.

**Comment by andreaskundig** [comment]
I don't know if this helps with material ui **Links**, but this works with **Buttons** and **ListItems**
```    
import React from 'react';
import { LinkProps } from "react-router-dom";
import { HashLink } from 'react-router-hash-link';
export const WrappedRouterLink = React.forwardRef<HTMLAnchorElement, LinkProps>((props) => (
    <HashLink   {...props} />
));
```    
Then I use a material-ui Button this way:
```        
<Button color="inherit" component={WrappedRouterLink} to="/doc">
          About
  </Button>
```

**Comment by Sphinxs** [comment]
React Router 6 doesn't export LinkProps

**Comment by vicary** [comment]
@andreaskundig Yes, that's another way to fake the type system. But still, material-ui needs to fix their typings to cope with `forwardRef()` if they are still relying on it. Keeping a close eye on [this comment](https://github.com/mui-org/material-ui/issues/20012#issuecomment-612820083).

**Comment by vicary** [comment]
@Sphinxs Usually `React.ComponentProps<Link>` works, you may try your luck. 🤞🏻

**Comment by rafgraph** [comment]
v2 of `react-router-hash-link` implements `React.forwardRef(...)`
