### ISSUE TITLE
Active style doesn't change when doing a normal scroll

### ISSUE THREAD

**Issue by Piyush-Paliwal** [rafgraph/react-router-hash-link#71]
Active style doesn't change when doing a normal scroll from page to page it only changes when clicking on a particular link.

**Comment by rafgraph** [comment]
Active style matches the current url. The url changes when clicking on a link, but not when simply scrolling to an element. This is standard behavior of how element `id`s and links work in html. If you want the active style to change on normal scroll, you'll have to change the url  using `history.push(...)` when the element is scrolled into view, which is out of scope of the library.
