### ISSUE TITLE
How to control isActive property

### ISSUE THREAD

**Issue by tomcanac** [rafgraph/react-router-hash-link#72]
Hi,

I managed to use window.history.replaceState to push anchors to the URL at scroll on my app page.
It works well, but my URL update doesn't change the current isActive anchor button.

- is it normal that it doesn't update automatically?
- can I control the current isActive myself? I noticed the isActive property, but I cannot send anything there, a boolean property would be great, but I can't really find any doc on how to use this property.

Any help on how to sync the isActive property with self updated URL hash would be amazing,
thanks for the library, it helps a lot!

**Comment by rafgraph** [comment]
Try using Rect Router's `replaceState` function, not the one on the window, otherwise React Router doesn't know the url has changed. If you provide an `isActive` prop it is passed through to React Router's `<Link>`, so see the React Router docs (you should be able to pass in a boolean).

**Comment by tomcanac** [comment]
good, thanks for the information! Indeed it does work with importing the history object from my main app.

Thanks for the help!
