### ISSUE TITLE
Update hash as the user scrolls through a page

### ISSUE THREAD

**Issue by mfilteau** [rafgraph/react-router-hash-link#79]
Consider a navbar where links can go to sections on a page or to a different page. When a user scrolls through a page and a new section become visible, it would be great if the corresponding section's hash gets updated on the browser's location and the corresponding navbar link becomes active.

The react-scroll library supports this feature but unfortunately only handles links within the current page.

**Comment by rafgraph** [comment]
HI, thanks for the suggestion, but unfortunately that is out of scope for this library. You can implement the detection yourself (using something like Intersection Observer), and then use `history.push(...)` to update the hash in the url.
