### ISSUE TITLE
Apply and remove active class and styling on NavHashLink when sections come into view

### ISSUE THREAD

**Issue by ruru-ink** [rafgraph/react-router-hash-link#85]
Using [section two of the demo](https://react-router-hash-link.rafgraph.dev/page#section-two) as an example, the link gets active styling when clicked on or page refreshed. This behaviour is as I'd expect. 

When the user scrolls down or up, the active styling on the "Section Two NavHashLink" link sticks, it's not removed. I would expect that link too revert back to the default styling. 

As you scroll down to "Section Three", I would expect the "Section Three NavHashLink" link to automatically get the activeClassName and activeStyle applied then reverted back to the default styling as I scroll back up.

**Comment by rafgraph** [comment]
Hi @ruru-ink, currently this is out of scope, see https://github.com/rafgraph/react-router-hash-link/issues/79#issuecomment-832369052. If you implement it yourself with `history.push(...)`, the active className and style will update when the hash changes.

I'd be interested in exploring adding this if someone wants to work on it, but there are a lot of edge cases (when there are multiple elements showing which one is active, etc) that make a good generic solution hard to design. If you're interested, please start a new issue with some ideas for how to implement it.

**Comment by ruru-ink** [comment]
Fair enough. 

If anyone comes across this and needs this behaviour, I've forked the demo and added the functionality using useInView within the react-intersection-observer package.

https://codesandbox.io/s/distracted-perlman-j4c5k
