### ISSUE TITLE
React router v6 support

### ISSUE THREAD

**Issue by charlesomer** [rafgraph/react-router-hash-link#86]
Hi,

Just wondered if it's possible to use this with React Router V6 or if it's been tried?

Thank you
Charles

**Comment by rafgraph** [comment]
I haven’t tried it yet. I’m sure others are curios too. If you try it let us know if it works!

**Comment by charlesomer** [comment]
Hmm I'm not completely sure how to test it, trying to just install the module fails because it doesn't recognise the beta release of React Router. I tried cloning and importing manually but it wasn't happy about that either 😂

**Comment by charlesomer** [comment]
Never mind, forgot about `--force`. Managed to get it installed and it _seems_ to work okay!

**Comment by charlesomer** [comment]
On a slightly separate note, is it possible to scroll to top automatically if no # is present in the link?

**Comment by rafgraph** [comment]
Great, glad it works!

To scroll to top without `#` or `#top` you’ll need to do this manually in your `onClick` handler.
